wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.6
    cli_version: 0.17.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719082899
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      - 37
      4: 3.7.6
      5: 0.17.2
      8:
      - 3
      - 5
      13: windows-amd64
batch_size:
  desc: null
  value: 64
buffer_size:
  desc: null
  value: 100000
exploration_final_eps:
  desc: null
  value: 0.09413689060535166
exploration_fraction:
  desc: null
  value: 0.1387508941448244
gamma:
  desc: null
  value: 0.9365285215448956
learning_rate:
  desc: null
  value: 0.00028331699928800253
policy_type:
  desc: null
  value: MlpPolicy
target_update_interval:
  desc: null
  value: 2000
total_timesteps:
  desc: null
  value: 20000
train_freq:
  desc: null
  value: 4
