wandb_version: 1

batch_size:
  value: 64
buffer_size:
  value: 100000
exploration_final_eps:
  value: 0.09214664727875216
exploration_fraction:
  value: 0.24217315633609376
gamma:
  value: 0.916884603876688
learning_rate:
  value: 0.0007695104486282169
policy_type:
  value: MlpPolicy
target_update_interval:
  value: 500
total_timesteps:
  value: 10000
train_freq:
  value: 8
