wandb_version: 1

batch_size:
  value: 32
buffer_size:
  value: 100000
exploration_final_eps:
  value: 0.030000567303816943
exploration_fraction:
  value: 0.24135598736084127
gamma:
  value: 0.9714848722108632
learning_rate:
  value: 0.0006620140061673728
policy_type:
  value: MlpPolicy
target_update_interval:
  value: 500
total_timesteps:
  value: 30000
train_freq:
  value: 8
