wandb_version: 1

batch_size:
  value: 128
buffer_size:
  value: 100000
exploration_final_eps:
  value: 0.05073777784023215
exploration_fraction:
  value: 0.13767469180249725
gamma:
  value: 0.921820831629232
learning_rate:
  value: 0.00026125051513764373
policy_type:
  value: MlpPolicy
target_update_interval:
  value: 2000
total_timesteps:
  value: 10000
train_freq:
  value: 16
