wandb_version: 1

batch_size:
  value: 128
buffer_size:
  value: 100000
exploration_final_eps:
  value: 0.09375661811090402
exploration_fraction:
  value: 0.31376270754446833
gamma:
  value: 0.9119659171565772
learning_rate:
  value: 0.000197000361733832
policy_type:
  value: MlpPolicy
target_update_interval:
  value: 2000
total_timesteps:
  value: 20000
train_freq:
  value: 8
