wandb_version: 1

batch_size:
  value: 128
buffer_size:
  value: 50000
exploration_final_eps:
  value: 0.05631635397948094
exploration_fraction:
  value: 0.4030734384366318
gamma:
  value: 0.9287081162396938
learning_rate:
  value: 0.0009744865465701564
policy_type:
  value: MlpPolicy
target_update_interval:
  value: 1000
total_timesteps:
  value: 10000
train_freq:
  value: 16
