wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.6
    cli_version: 0.17.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719082927
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      - 37
      4: 3.7.6
      5: 0.17.2
      8:
      - 3
      - 5
      13: windows-amd64
batch_size:
  desc: null
  value: 32
buffer_size:
  desc: null
  value: 50000
exploration_final_eps:
  desc: null
  value: 0.08195637274465419
exploration_fraction:
  desc: null
  value: 0.3595132937360219
gamma:
  desc: null
  value: 0.9114634014386468
learning_rate:
  desc: null
  value: 0.000872751287060942
policy_type:
  desc: null
  value: MlpPolicy
target_update_interval:
  desc: null
  value: 1000
total_timesteps:
  desc: null
  value: 30000
train_freq:
  desc: null
  value: 16
